# Generated by Django 2.2.10 on 2020-03-09 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plagiantapp', '0002_auto_20200309_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='university_name',
            field=models.ForeignKey(blank=True, default='Universitet', null=True, on_delete=django.db.models.deletion.CASCADE, to='plagiantapp.University'),
        ),
    ]
