# Generated by Django 2.2.10 on 2020-03-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagiantapp', '0004_auto_20200309_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
