# Generated by Django 2.2.10 on 2020-03-19 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plagiantapp', '0005_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='static/original_document')),
                ('document_title', models.TextField(max_length=300)),
                ('student_name', models.TextField(max_length=100)),
                ('teacher_name', models.TextField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plagiantapp.University')),
            ],
        ),
    ]
