# Generated by Django 2.2.10 on 2020-03-19 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plagiantapp', '0006_originaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='originaldocument',
            name='document_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='originaldocument',
            name='document_title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='originaldocument',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='originaldocument',
            name='teacher_name',
            field=models.CharField(max_length=100),
        ),
    ]
