# Generated by Django 2.2.10 on 2020-03-19 23:28

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('plagiantapp', '0009_auto_20200319_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originaldocument',
            name='checked_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
