# Generated by Django 2.2.10 on 2020-03-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plagiantapp', '0010_auto_20200319_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originaldocument',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plagiantapp.University'),
        ),
    ]
