# Generated by Django 2.2.10 on 2020-03-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plagiantapp', '0011_auto_20200321_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='originaldocument',
            old_name='checked_by',
            new_name='uploaded_by',
        ),
    ]
